#server:
#  port: 8084
#
#spring:
#  datasource:
#    url: jdbc:postgresql://db:5432/bank_system
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: admin
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        temp:
#          use_jdbc_metadata_defaults: true


spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://db:5432/test

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8084